# Generated by Django 3.1.2 on 2020-10-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Nickname', models.CharField(max_length=20)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Age', models.IntegerField(default=0)),
                ('Friends', models.ManyToManyField(related_name='_viewer_Friends_+', to='movies.Viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('RSVPs', models.IntegerField(default=0)),
                ('MovieTitle', models.CharField(max_length=100)),
                ('AgeRating', models.IntegerField(default=0)),
                ('SID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Language', models.CharField(max_length=20)),
                ('YearProduced', models.IntegerField(default=0)),
                ('TimeAt', models.TimeField()),
                ('DateAt', models.DateTimeField()),
                ('Tickets', models.ManyToManyField(to='movies.Viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenreTitle', models.CharField(max_length=30)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.screening')),
            ],
        ),
    ]
