# Generated by Django 3.1.2 on 2020-10-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='SID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='Username',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
