# Generated by Django 3.1.2 on 2020-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201018_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='Username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
