# Generated by Django 3.1.2 on 2020-10-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201018_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='Tickets',
            field=models.ManyToManyField(blank=True, to='movies.Viewer'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='Friends',
            field=models.ManyToManyField(blank=True, related_name='_viewer_Friends_+', to='movies.Viewer'),
        ),
    ]
