# Generated by Django 3.1.2 on 2020-10-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201018_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viewer1', to='movies.viewer')),
                ('Username2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viewer2', to='movies.viewer')),
            ],
        ),
    ]
