# Generated by Django 3.1.2 on 2020-10-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='Tickets',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='Friends',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScreeningNum', to='movies.screening')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viewer', to='movies.screening')),
            ],
        ),
    ]
