# Generated by Django 3.1.2 on 2020-10-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201018_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='TimeAt',
        ),
    ]
