# Generated by Django 3.1.2 on 2020-10-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_screening_timeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viewer', to='movies.viewer'),
        ),
    ]
